version: "3"
services:
  client:
    build: ./polafide-client
    restart: always
    environment:
      - PRODUCTION='true'
    ports:
      - "80:8080"
  search:
    build: ./search-service
    restart: always
    environment:
      - PRODUCTION='true'
      - PLACES_API_KEY=""
  reviews:
    build: ./reviews-service
    restart: always
    environment:
      - DEBUG='false'
      - PRODUCTION='true'
      - PLACES_API_KEY=""
      - DB_URI="mongodb://prod_kyle:clipper01@ds151048.mlab.com:51048/polafide-reviews"

