# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ba8242e09e233107186c3ae71a0d49b6a83b8ba117c7a404b0ca4fa30e68e6b25c08a273a39fcaa3221dafab1a1ab66cd067715cd5054475a8408920a583710

test:
  secret_key_base: 80430605541971843eaf90a287978981ec68f4f760b398ac5a37f15949251fa6c7eb30ddaa13335b9f7f947f371762c51d7b4e2cdb55ffd3555523e7fcad44b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
