# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdd4e7f7d72793ddf8e8baf752ecca64f7617240ee4bba7afa1dae56a06470c93a4d8468472cad6b77f93e49257d8e73fcaf6174ab66a4b393988d1837fb5fb6

test:
  secret_key_base: 3440e8206956cc67a2b9d2f81a93181bbd0759e08b73a8efb881b4dce3ed1ba00b8e294cbd5e5e0557d7f383cbe4943206b5571fa512ded5290766c6f9e4aa3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
